#!/bin/bash 

LOG=$HOME/logs/codzienny.log
DJANGODIR=$HOME/django

source $HOME/bin/activate

echo " " >> ${LOG}
date >> ${LOG}
python $HOME/download/codzienny.py &>> ${LOG}
sleep 5
python ${DJANGODIR}/manage.py loadnew codzienny &>> ${LOG}
