#!/bin/bash 

LOG=$HOME/logs/zacny.log
DJANGODIR=$HOME/django

source $HOME/bin/activate

echo " " >> ${LOG}
date >> ${LOG}
$HOME/download/zacny.py &>> ${LOG}
sleep 5
python ${DJANGODIR}/manage.py loadnew zacny &>> ${LOG}
