#!/bin/bash 

LOG=$HOME/logs/wykop.log
DJANGODIR=$HOME/django

source $HOME/bin/activate

echo " " >> ${LOG}
date >> ${LOG}
python $HOME/download/mirko.py &>> ${LOG}
sleep 5
python ${DJANGODIR}/manage.py loadnew wykop &>> ${LOG}
